/*Antarktis und Arktis werden zu Ozeanen gezählt
Kontinente:
Europa: "eu"
Asien: "as"
Nordamerika: "na"
Südamerika: "sa"
Ozeanien: "oz"
*/

export default [
  { code: "ad", german: "Andorra", continent: "eu" },
  { code: "ae", german: "Vereinigte Arabische Emirate", continent: "as" },
  { code: "af", german: "Afghanistan", continent: "as" },
  { code: "ag", german: "Antigua und Barbuda", continent: "na" },
  { code: "ai", german: "Anguilla", continent: "sa" },
  { code: "al", german: "Albanien", continent: "eu" },
  { code: "am", german: "Armenien", continent: "as" },
  { code: "ao", german: "Angola", continent: "af" },
  { code: "aq", german: "Antarktis", continent: "oz" },
  { code: "ar", german: "Argentinien", continent: "sa" },
  { code: "as", german: "Amerikanisch-Samoa", continent: "oz" },
  { code: "at", german: "Österreich", continent: "eu" },
  { code: "au", german: "Australien", continent: "oz" },
  { code: "aw", german: "Aruba", continent: "sa" },
  { code: "ax", german: "Åland", continent: "eu" },
  { code: "az", german: "Aserbaidschan", continent: "as" },
  { code: "ba", german: "Bosnien und Herzegowina", continent: "eu" },
  { code: "bb", german: "Barbados", continent: "na" },
  { code: "bd", german: "Bangladesch", continent: "as" },
  { code: "be", german: "Belgien", continent: "eu" },
  { code: "bf", german: "Burkina Faso", continent: "af" },
  { code: "bg", german: "Bulgarien", continent: "eu" },
  { code: "bh", german: "Bahrain", continent: "as" },
  { code: "bi", german: "Burundi", continent: "af" },
  { code: "bj", german: "Benin", continent: "af" },
  { code: "bl", german: "Saint-Barthélemy", continent: "na" },
  { code: "bm", german: "Bermuda", continent: "na" },
  { code: "bn", german: "Brunei", continent: "af" },
  { code: "bo", german: "Bolivien", continent: "sa" },
  { code: "bq", german: "Karibische Niederlande", continent: "sa" },
  { code: "br", german: "Brasilien", continent: "sa" },
  { code: "bs", german: "Bahamas", continent: "sa" },
  { code: "bt", german: "Bhutan", continent: "as" },
  { code: "bw", german: "Botswana", continent: "af" },
  { code: "by", german: "Weißrussland", continent: "eu" },
  { code: "bz", german: "Belize", continent: "na" },
  { code: "ca", german: "Kanada", continent: "na" },
  { code: "cc", german: "Kokosinseln", continent: "oz" },
  { code: "cd", german: "Kongo (Dem. Rep.)", continent: "af" },
  { code: "cf", german: "Zentralafrikanische Republik", continent: "af" },
  { code: "cg", german: "Kongo", continent: "af" },
  { code: "ch", german: "Schweiz", continent: "eu" },
  { code: "ci", german: "Elfenbeinküste", continent: "af" },
  { code: "ck", german: "Cookinseln", continent: "oz" },
  { code: "cl", german: "Chile", continent: "sa" },
  { code: "cm", german: "Kamerun", continent: "af" },
  { code: "cn", german: "China", continent: "as" },
  { code: "co", german: "Kolumbien", continent: "sa" },
  { code: "cr", german: "Costa Rica", continent: "na" },
  { code: "cu", german: "Kuba", continent: "na" },
  { code: "cv", german: "Kap Verde", continent: "af" },
  { code: "cw", german: "Curaçao", continent: "sa" },
  { code: "cx", german: "Weihnachtsinsel", continent: "oz" },
  { code: "cy", german: "Zypern", continent: "eu" },
  { code: "cz", german: "Tschechien", continent: "eu" },
  { code: "de", german: "Deutschland", continent: "eu" },
  { code: "dj", german: "Dschibuti", continent: "af" },
  { code: "dk", german: "Dänemark", continent: "eu" },
  { code: "dm", german: "Dominica", continent: "na" },
  { code: "do", german: "Dominikanische Republik", continent: "na" },
  { code: "dz", german: "Algerien", continent: "af" },
  { code: "ec", german: "Ecuador", continent: "sa" },
  { code: "ee", german: "Estland", continent: "eu" },
  { code: "eg", german: "Ägypten", continent: "af" },
  { code: "eh", german: "Westsahara", continent: "af" },
  { code: "er", german: "Eritrea", continent: "af" },
  { code: "es", german: "Spanien", continent: "eu" },
  { code: "et", german: "Äthiopien", continent: "eu" },
  { code: "fi", german: "Finnland", continent: "eu" },
  { code: "fj", german: "Fidschi", continent: "oz" },
  { code: "fk", german: "Falklandinseln", continent: "sa" },
  { code: "fm", german: "Mikronesien", continent: "oz" },
  { code: "fo", german: "Färöer-Inseln", continent: "eu" },
  { code: "fr", german: "Frankreich", continent: "eu" },
  { code: "ga", german: "Gabun", continent: "af" },
  { code: "gb", german: "Vereinigtes Königreich", continent: "eu" },
  { code: "gb-eng", german: "England", continent: "eu" },
  { code: "gb-nir", german: "Nordirland", continent: "eu" },
  { code: "gb-sct", german: "Schottland", continent: "eu" },
  { code: "gb-wls", german: "Wales", continent: "eu" },
  { code: "gd", german: "Grenada", continent: "na" },
  { code: "ge", german: "Georgien", continent: "as" },
  { code: "gf", german: "Französisch-Guayana", continent: "sa" },
  { code: "gg", german: "Guernsey", continent: "eu" },
  { code: "gh", german: "Ghana", continent: "af" },
  { code: "gi", german: "Gibraltar", continent: "eu" },
  { code: "gl", german: "Grönland", continent: "na" },
  { code: "gm", german: "Gambia", continent: "af" },
  { code: "gn", german: "Guinea", continent: "af" },
  { code: "gp", german: "Guadeloupe", continent: "na" },
  { code: "gq", german: "Äquatorialguinea", continent: "af" },
  { code: "gr", german: "Griechenland", continent: "eu" },
  { code: "gt", german: "Guatemala", continent: "na" },
  { code: "gu", german: "Guam", continent: "oz" },
  { code: "gw", german: "Guinea-Bissau", continent: "af" },
  { code: "gy", german: "Guyana", continent: "sa" },
  { code: "hn", german: "Honduras", continent: "na" },
  { code: "hr", german: "Kroatien", continent: "eu" },
  { code: "ht", german: "Haiti", continent: "na" },
  { code: "hu", german: "Ungarn", continent: "eu" },
  { code: "id", german: "Indonesien", continent: "as" },
  { code: "ie", german: "Irland", continent: "eu" },
  { code: "il", german: "Israel", continent: "as" },
  { code: "im", german: "Isle of Man", continent: "eu" },
  { code: "in", german: "Indien", continent: "as" },
  {
    code: "io",
    german: "Britisches Territorium im Indischen Ozean",
    continent: "as",
  },
  { code: "iq", german: "Irak", continent: "as" },
  { code: "ir", german: "Iran", continent: "as" },
  { code: "is", german: "Island", continent: "eu" },
  { code: "it", german: "Italien", continent: "eu" },
  { code: "je", german: "Jersey", continent: "eu" },
  { code: "jm", german: "Jamaika", continent: "na" },
  { code: "jo", german: "Jordanien", continent: "as" },
  { code: "jp", german: "Japan", continent: "as" },
  { code: "ke", german: "Kenia", continent: "af" },
  { code: "kg", german: "Kirgisistan", continent: "as" },
  { code: "kh", german: "Kambodscha", continent: "as" },
  { code: "ki", german: "Kiribati", continent: "oz" },
  { code: "km", german: "Komoren", continent: "af" },
  { code: "kn", german: "St. Kitts und Nevis", continent: "na" },
  { code: "kp", german: "Nordkorea", continent: "as" },
  { code: "kr", german: "Südkorea", continent: "as" },
  { code: "kw", german: "Kuwait", continent: "as" },
  { code: "ky", german: "Kaimaninseln", continent: "na" },
  { code: "kz", german: "Kasachstan", continent: "as" },
  { code: "la", german: "Laos", continent: "as" },
  { code: "lb", german: "Libanon", continent: "as" },
  { code: "lc", german: "St. Lucia", continent: "na" },
  { code: "li", german: "Liechtenstein", continent: "eu" },
  { code: "lk", german: "Sri Lanka", continent: "as" },
  { code: "lr", german: "Liberia", continent: "af" },
  { code: "ls", german: "Lesotho", continent: "af" },
  { code: "lt", german: "Litauen", continent: "eu" },
  { code: "lu", german: "Luxemburg", continent: "eu" },
  { code: "lv", german: "Lettland", continent: "eu" },
  { code: "ly", german: "Libyen", continent: "af" },
  { code: "ma", german: "Marokko", continent: "af" },
  { code: "mc", german: "Monaco", continent: "eu" },
  { code: "md", german: "Moldawien", continent: "eu" },
  { code: "me", german: "Montenegro", continent: "eu" },
  { code: "mf", german: "Saint-Martin", continent: "na" },
  { code: "mg", german: "Madagaskar", continent: "af" },
  { code: "mh", german: "Marshallinseln", continent: "oz" },
  { code: "mk", german: "Nordmazedonien", continent: "eu" },
  { code: "ml", german: "Mali", continent: "af" },
  { code: "mm", german: "Myanmar", continent: "as" },
  { code: "mn", german: "Mongolei", continent: "as" },
  { code: "mp", german: "Nördliche Marianen", continent: "oz" },
  { code: "mr", german: "Mauretanien", continent: "af" },
  { code: "ms", german: "Montserrat", continent: "na" },
  { code: "mt", german: "Malta", continent: "eu" },
  { code: "mu", german: "Mauritius", continent: "af" },
  { code: "mv", german: "Malediven", continent: "as" },
  { code: "mw", german: "Malawi", continent: "af" },
  { code: "mx", german: "Mexiko", continent: "na" },
  { code: "my", german: "Malaysia", continent: "as" },
  { code: "mz", german: "Mosambik", continent: "af" },
  { code: "na", german: "Namibia", continent: "af" },
  { code: "nc", german: "Neukaledonien", continent: "oz" },
  { code: "ne", german: "Niger", continent: "af" },
  { code: "nf", german: "Norfolkinsel", continent: "oz" },
  { code: "ng", german: "Nigeria", continent: "af" },
  { code: "ni", german: "Nicaragua", continent: "na" },
  { code: "nl", german: "Niederlande", continent: "eu" },
  { code: "no", german: "Norwegen", continent: "eu" },
  { code: "np", german: "Nepal", continent: "as" },
  { code: "nr", german: "Nauru", continent: "oz" },
  { code: "nu", german: "Niue", continent: "oz" },
  { code: "nz", german: "Neuseeland", continent: "oz" },
  { code: "om", german: "Oman", continent: "as" },
  { code: "pa", german: "Panama", continent: "na" },
  { code: "pe", german: "Peru", continent: "sa" },
  { code: "pf", german: "Französisch-Polynesien", continent: "oz" },
  { code: "pg", german: "Papua-Neuguinea", continent: "oz" },
  { code: "ph", german: "Philippinen", continent: "as" },
  { code: "pk", german: "Pakistan", continent: "as" },
  { code: "pl", german: "Polen", continent: "eu" },
  { code: "pm", german: "St. Pierre und Miquelon", continent: "na" },
  { code: "pn", german: "Pitcairninseln", continent: "oz" },
  { code: "pr", german: "Puerto Rico", continent: "na" },
  { code: "ps", german: "Palästina", continent: "as" },
  { code: "pt", german: "Portugal", continent: "eu" },
  { code: "pw", german: "Palau", continent: "oz" },
  { code: "py", german: "Paraguay", continent: "sa" },
  { code: "qa", german: "Katar", continent: "as" },
  { code: "ro", german: "Rumänien", continent: "eu" },
  { code: "rs", german: "Serbien", continent: "eu" },
  { code: "ru", german: "Russland", continent: "as" },
  { code: "rw", german: "Ruanda", continent: "af" },
  { code: "sa", german: "Saudi-Arabien", continent: "as" },
  { code: "sb", german: "Salomonen", continent: "oz" },
  { code: "sc", german: "Seychellen", continent: "af" },
  { code: "sd", german: "Sudan", continent: "af" },
  { code: "se", german: "Schweden", continent: "eu" },
  { code: "sg", german: "Singapur", continent: "as" },
  {
    code: "sh",
    german: "St. Helena, Ascension und Tristan da Cunha",
    continent: "af",
  },
  { code: "si", german: "Slowenien", continent: "eu" },
  { code: "sk", german: "Slowakei", continent: "eu" },
  { code: "sl", german: "Sierra Leone", continent: "af" },
  { code: "sm", german: "San Marino", continent: "eu" },
  { code: "sn", german: "Senegal", continent: "af" },
  { code: "so", german: "Somalia", continent: "af" },
  { code: "sr", german: "Suriname", continent: "sa" },
  { code: "ss", german: "Südsudan", continent: "af" },
  { code: "st", german: "São Tomé und Príncipe", continent: "af" },
  { code: "sv", german: "El Salvador", continent: "na" },
  { code: "sx", german: "Sint Maarten", continent: "na" },
  { code: "sy", german: "Syrien", continent: "as" },
  { code: "sz", german: "Swasiland", continent: "af" },
  { code: "tc", german: "Turks-und Caicosinseln", continent: "na" },
  { code: "td", german: "Tschad", continent: "af" },
  { code: "tg", german: "Togo", continent: "af" },
  { code: "th", german: "Thailand", continent: "as" },
  { code: "tj", german: "Tadschikistan", continent: "as" },
  { code: "tk", german: "Tokelau", continent: "oz" },
  { code: "tl", german: "Osttimor", continent: "as" },
  { code: "tm", german: "Turkmenistan", continent: "as" },
  { code: "tn", german: "Tunesien", continent: "af" },
  { code: "to", german: "Tonga", continent: "oz" },
  { code: "tr", german: "Türkei", continent: "as" },
  { code: "tt", german: "Trinidad und Tobago", continent: "na" },
  { code: "tv", german: "Tuvalu", continent: "oz" },
  { code: "tw", german: "Taiwan", continent: "as" },
  { code: "tz", german: "Tansania", continent: "af" },
  { code: "ua", german: "Ukraine", continent: "eu" },
  { code: "ug", german: "Uganda", continent: "af" },
  { code: "us", german: "Vereinigte Staaten", continent: "na" },
  { code: "uy", german: "Uruguay", continent: "sa" },
  { code: "uz", german: "Usbekistan", continent: "as" },
  { code: "va", german: "Vatikanstadt", continent: "eu" },
  { code: "vc", german: "St. Vincent und die Grenadinen", continent: "na" },
  { code: "ve", german: "Venezuela", continent: "sa" },
  { code: "vg", german: "Britische Jungferninseln", continent: "na" },
  { code: "vi", german: "Amerikanische Jungferninseln", continent: "na" },
  { code: "vn", german: "Vietnam", continent: "as" },
  { code: "vu", german: "Vanuatu", continent: "oz" },
  { code: "wf", german: "Wallis und Futuna", continent: "oz" },
  { code: "ws", german: "Samoa", continent: "oz" },
  { code: "xk", german: "Kosovo", continent: "eu" },
  { code: "ye", german: "Jemen", continent: "as" },
  { code: "yt", german: "Mayotte", continent: "af" },
  { code: "za", german: "Südafrika", continent: "sa" },
  { code: "zm", german: "Sambia", continent: "af" },
  { code: "zw", german: "Simbabwe", continent: "af" },
];
